In [7]:
%config IPcompleter.use_jedi=False
import pandas as pd

In [8]:
df = pd.read_csv('heart_disease_dataset.csv')

In [9]:
df

age;sex;chest_pain_type;resting_blood_pressure;cholesterol;fasting_blood_sugar;rest_ecg;max_heart_rate_achieved;exercise_induced_angina;st_depression;st_slope;num_major_vessels;thalassemia;target
0                 63;1;3;145;233;1;0;150;0;2.3;0;0;1;1                                                                                                                                                 
1                 37;1;2;130;250;0;1;187;0;3.5;0;0;2;1                                                                                                                                                 
2                 41;0;1;130;204;0;0;172;0;1.4;2;0;2;1                                                                                                                                                 
3                 56;1;1;120;236;0;1;178;0;0.8;2;0;2;1                                                                                                                                                 
4                 57;0;0;120;354;0;1;163;1;0.6;2;0;2;1                                                                                                                                                 
..                                                 ...                                                                                                                                                 
298               57;0;0;140;241;0;1;123;1;0.2;1;0;3;0                                                                                                                                                 
299               45;1;3;110;264;0;1;132;0;1.2;1;0;3;0                                                                                                                                                 
300               68;1;0;144;193;1;1;141;0;3.4;1;2;3;0                                                                                                                                                 
301               57;1;0;130;131;0;1;115;1;1.2;1;1;3;0                                                                                                                                                 
302               57;0;1;130;236;0;0;174;0;0.0;1;1;2;0                                                                                                                                                 

[303 rows x 1 columns]

In [10]:
df.head()

age;sex;chest_pain_type;resting_blood_pressure;cholesterol;fasting_blood_sugar;rest_ecg;max_heart_rate_achieved;exercise_induced_angina;st_depression;st_slope;num_major_vessels;thalassemia;target
0               63;1;3;145;233;1;0;150;0;2.3;0;0;1;1                                                                                                                                                 
1               37;1;2;130;250;0;1;187;0;3.5;0;0;2;1                                                                                                                                                 
2               41;0;1;130;204;0;0;172;0;1.4;2;0;2;1                                                                                                                                                 
3               56;1;1;120;236;0;1;178;0;0.8;2;0;2;1                                                                                                                                                 
4               57;0;0;120;354;0;1;163;1;0.6;2;0;2;1

In [11]:
df.describe()

age;sex;chest_pain_type;resting_blood_pressure;cholesterol;fasting_blood_sugar;rest_ecg;max_heart_rate_achieved;exercise_induced_angina;st_depression;st_slope;num_major_vessels;thalassemia;target
count                                                 303                                                                                                                                                 
unique                                                302                                                                                                                                                 
top                  38;1;2;138;175;0;1;173;0;0.0;2;4;2;1                                                                                                                                                 
freq                                                    2

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                               Non-Null Count  Dtype 
---  ------                                                                                                                                                                                               --------------  ----- 
 0   age;sex;chest_pain_type;resting_blood_pressure;cholesterol;fasting_blood_sugar;rest_ecg;max_heart_rate_achieved;exercise_induced_angina;st_depression;st_slope;num_major_vessels;thalassemia;target  303 non-null    object
dtypes: object(1)
memory usage: 2.5+ KB


In [13]:
df.isnull().sum()

age;sex;chest_pain_type;resting_blood_pressure;cholesterol;fasting_blood_sugar;rest_ecg;max_heart_rate_achieved;exercise_induced_angina;st_depression;st_slope;num_major_vessels;thalassemia;target    0
dtype: int64

In [4]:
import numpy as np

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def mse_loss(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return ((y_true - y_pred) ** 2).mean()

def mse_loss_derivative(y_true, y_pred):
  # y_true and y_pred are numpy arrays of the same length.
  return (2*(y_true - y_pred))

class ArtificialNeuralNetwork:
    def __init__(self, x, y):
        self.IN      = x
        self.W1   = np.random.rand(self.IN.shape[1],6)
        self.W2   = np.random.rand(6,4)
        self.W3   = np.random.rand(4,1)                 
        self.y          = y
        self.OUT     = np.zeros(self.y.shape)
        self.learning_rate = 0.3

    def feed_forward(self):
        self.HIDDEN_LAYER_1 = sigmoid(np.dot(self.IN, self.W1))
        self.HIDDEN_LAYER_2 = sigmoid(np.dot(self.HIDDEN_LAYER_1, self.W2))
        self.output = sigmoid(np.dot(self.HIDDEN_LAYER_2, self.W3))

    #def back_propagate(self):
        # application of the chain rule to find derivative of the loss function with respect to W2 and W1
        #print(self.HIDDEN_LAYER_1.T)
        #d_W2 = np.dot(self.HIDDEN_LAYER_1.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        #print(d_W2)
        #d_W1 = np.dot(self.IN.T,  (np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W2.T) * sigmoid_derivative(self.HIDDEN_LAYER_1)))
        
                
    def back_propagate(self):
         # application of the chain rule to find derivative of the loss function with respect to W3,W2,W1
        print(self.HIDDEN_LAYER_2.T)
        d_W3 = np.dot(self.HIDDEN_LAYER_2.T, (mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output)))
        print(d_W3)
        d_W2 = np.dot(self.HIDDEN_LAYER_1.T,  (np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2)))
        print(d_W3)
        d_W1 = np.dot(self.IN.T,  (np.dot(np.dot(mse_loss_derivative(self.y, self.output) * sigmoid_derivative(self.output), self.W3.T) * sigmoid_derivative(self.HIDDEN_LAYER_2),self.W2.T)*sigmoid_derivative(self.HIDDEN_LAYER_1)))  




        # update the weights with the derivative (slope) of the loss function
        self.W1 += self.learning_rate*d_W1
        self.W2 += self.learning_rate*d_W2
        self.W3 += self.learning_rate*d_W3

    def train(self, epochs,learning_rate):
        self.learning_rate=learning_rate
        for i in range(epochs):
            self.feed_forward()
            self.back_propagate()
        print("Successfully Trained the Model")
        print("Weights 1:", self.W1)
        print("Weights 2:", self.W2)
        print(("Weights 3:", self.W3))
    
    def print_output(self):
        print(self.output)



In [5]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
y = np.array([[0],[1],[1],[0]])
epochs = 2
learning_rate = 0.5
ann = ArtificialNeuralNetwork(X,y)
ann.train(epochs, learning_rate)

[[0.84231811 0.89229807 0.88596302 0.91653574]
 [0.86612324 0.90564647 0.89770541 0.92454213]
 [0.80286662 0.8537208  0.84899302 0.8811434 ]
 [0.84866252 0.88605692 0.87686734 0.90420205]]
[[-0.32228093]
 [-0.32853086]
 [-0.30851125]
 [-0.32170828]]
[[-0.32228093]
 [-0.32853086]
 [-0.30851125]
 [-0.32170828]]
[[0.83991318 0.89022508 0.88382488 0.91473611]
 [0.86131633 0.90134823 0.89319988 0.92064862]
 [0.80023784 0.85123595 0.84649892 0.87886008]
 [0.84585878 0.88340797 0.87408937 0.90169223]]
[[-0.32746162]
 [-0.33327484]
 [-0.31333588]
 [-0.32707099]]
[[-0.32746162]
 [-0.33327484]
 [-0.31333588]
 [-0.32707099]]
Successfully Trained the Model
Weights 1: [[0.29654439 0.17032412 0.11340934 0.87809898 0.91545975 0.66423357]
 [0.22942134 0.62603485 0.8601757  0.83820933 0.89181563 0.27920109]
 [0.55269644 0.96737558 0.3960174  0.19349996 0.02026247 0.18276129]]
Weights 2: [[0.32364704 0.47869765 0.02602868 0.43143235]
 [0.22025847 0.45996964 0.37493782 0.72248317]
 [0.67107537 0.81941025